# Generated by Django 4.2.16 on 2024-12-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knygynas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='complete',
            new_name='completed',
        ),
        migrations.AlterModelTable(
            name='todoitem',
            table='todos',
        ),
    ]
