# Generated by Django 4.2.16 on 2024-12-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knygynas', '0003_autorius_knyga_krepselioknyga_krepselis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knyga',
            options={'verbose_name': 'Knyga', 'verbose_name_plural': 'Knygos'},
        ),
        migrations.AddField(
            model_name='knyga',
            name='original_kaina',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
